### ISSUE TITLE
stylelint throws ERR_INVALID_URL_SCHEME when updating from 24.0.0 to 25.0.0

### ISSUE THREAD

**Issue by BePo65** [stylelint/stylelint-config-standard#239]
### What steps are needed to reproduce the bug?

When using stylelint@14.5.0 with stylelint-config-standard@24.0.0 the linting runs without any warnings / errors.

But after updating to stylelint-config-standard@24.0.0 stylelint throws and shows a stack trace.

My configuration runs on windows 10 with node 16.13.1

### What did you expect to happen?

Just the same result as with version 24.0.0

### What actually happened?

Stacktrace after updating to version 25.0.0
```
> npx stylelint "**/*.scss"

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\rules\function-no-unknown\index.js:48:39
    at D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\lintPostcssResult.js:113:8
    at Array.map (<anonymous>)
    at lintPostcssResult (D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\lintPostcssResult.js:104:18)
    at lintSource (D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\lintSource.js:91:8)
    at async D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\standalone.js:227:27
    at async Promise.all (index 0)
    at async standalone (D:\Projekte\github\mat-image-overlay\node_modules\stylelint\lib\standalone.js:266:22)
```

**Comment by jeddy3** [comment]
Thanks for the report.

We're tracking this in the Stylelint issue tracker: https://github.com/stylelint/stylelint/issues/5918

Closing.
