### ISSUE TITLE
Regression: Throwing syntax error when filter is repeatedy used after upgrading to v33

### ISSUE THREAD

**Issue by julianna-ciq** [stylelint/stylelint-config-standard#289]
### What steps are needed to reproduce the bug?

1. Create a file with this content (minimum reproducible example):
```css
div {
	filter: "";
	filter: alpha(opacity=20);
}
```

2. Run stylelint against that file (eg, `stylelint path/to/file.css`)
3. Get this error:
> SyntaxError: ")" is expected
    at TokenStream.error (...\node_modules\css-tree\cjs\parser\create.cjs:270:19)
    at TokenStream.eat (...\node_modules\css-tree\cjs\parser\create.cjs:218:22)
    at TokenStream.parse [as Function] (...\node_modules\css-tree\cjs\syntax\node\Function.cjs:24:14)
    at TokenStream.defaultRecognizer (...\node_modules\css-tree\cjs\syntax\scope\default.cjs:41:24)
    at TokenStream.readSequence (...\node_modules\css-tree\cjs\parser\sequence.cjs:24:40)
    at TokenStream.parse [as Value] (...\node_modules\css-tree\cjs\syntax\node\Value.cjs:10:27)
    at TokenStream.<anonymous> (...\node_modules\css-tree\cjs\parser\create.cjs:22:26)
    at parse (...\node_modules\css-tree\cjs\parser\create.cjs:321:45)

Note that the second line, `filter: ""`, is necessary. Without that line, you correctly get:
> 2:10 > Unexpected unknown function "alpha"  function-no-unknown

stylelint config for the minimally reproducible example:
```json
{
	"extends": ["stylelint-config-standard"],
	"rules": {
	}
}
```

This issue only arose after the v33 upgrade.

### What did you expect to happen?

I expected to only receive this message:
```
> 2:10 > Unexpected unknown function "alpha"  function-no-unknown
```

### What actually happened?

I got this error:
> SyntaxError: ")" is expected
    at TokenStream.error (...\node_modules\css-tree\cjs\parser\create.cjs:270:19)
    at TokenStream.eat (...\node_modules\css-tree\cjs\parser\create.cjs:218:22)
    at TokenStream.parse [as Function] (...\node_modules\css-tree\cjs\syntax\node\Function.cjs:24:14)
    at TokenStream.defaultRecognizer (...\node_modules\css-tree\cjs\syntax\scope\default.cjs:41:24)
    at TokenStream.readSequence (...\node_modules\css-tree\cjs\parser\sequence.cjs:24:40)
    at TokenStream.parse [as Value] (...\node_modules\css-tree\cjs\syntax\node\Value.cjs:10:27)
    at TokenStream.<anonymous> (...\node_modules\css-tree\cjs\parser\create.cjs:22:26)
    at parse (...\node_modules\css-tree\cjs\parser\create.cjs:321:45)

**Comment by ybiquitous** [comment]
@julianna-ciq Thanks for the report. We find this error is due to `declaration-block-no-duplicate-properties` (https://github.com/stylelint/stylelint/issues/6791), and you can avoid it via the workaround at this time:

```json
{
  "rules": {
    "declaration-block-no-duplicate-properties": null
  }
}
```

This fix for this problem has been merged already, and we will release it within a few days.
