### ISSUE TITLE
Undefined rule "block-closing-brace-empty-line-before"

### ISSUE THREAD

**Issue by marvinhagemeister** [stylelint/stylelint-config-standard#37]
Seems like a dependency is missing:

```bash
Error: Undefined rule "block-closing-brace-empty-line-before"
    at exports.default (/usr/local/lib/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /usr/local/lib/node_modules/stylelint/dist/postcssPlugin.js:113:47
    at Array.forEach (native)
    at /usr/local/lib/node_modules/stylelint/dist/postcssPlugin.js:111:33
```

**Comment by marvinhagemeister** [comment]
Found the culprit! I was calling stylelint via a makefile:

```bash
stylelint:
  @stylelint css/*.css
```

and changing that to the npm binary fixed it:

```bash
stylelint:
  @./node_modules/.bin/stylelint css/*.css
```
